### ISSUE TITLE
Upstream TLS fails with self-signed certs, works with standalone Agent

### ISSUE THREAD

**Issue by justngrok** [ngrok/ngrok-javascript#119]
Example: ngrok http https://localhost:443 -> works!

Fails with ERR_NGROK_3004
```
(async function () {
	const listener = await ngrok.forward({
		addr: 'https://localhost:443',
		authtoken_from_env: true,
	});

	console.log(`Ingress established at: ${listener.url()}`);
})();
```

This however does work (self-signed certs the issue)?
```
(async function () {
	const listener = await ngrok.forward({
		addr: 'https://google.com:443',
		authtoken_from_env: true,
	});

	console.log(`Ingress established at: ${listener.url()}`);
})();
```

**Comment by bobzilladev** [comment]
Hello! Aye, it defaults to host certs for TLS backends. To use with self-signing you need to specify the cert file with an environment variable, see the [tls-backends](https://github.com/ngrok/ngrok-javascript?tab=readme-ov-file#tls-backends) section in the readme for more info.

**Comment by bobzilladev** [comment]
There's a feature request to allow for unchecked backend tls connections over on the python side, it would be implemented in rust and could be plumbed through python+javascript: https://github.com/ngrok/ngrok-python/issues/88

**Comment by bobzilladev** [comment]
Going to close out this issue, feel free to reopen if there are further questions!
