### ISSUE TITLE
Reaping old .sock files?

### ISSUE THREAD

**Issue by russorat** [ngrok/ngrok-javascript#123]
After using the auto-update ability of nodemon to build an express app with ngrok-javascript, i noticed that there is a `.ngrok` folder containing a bunch of *.sock files. 

Is there a way to automatically reap those? Should this library clean them out on a regular basis? 

![image](https://github.com/ngrok/ngrok-javascript/assets/4805997/ce3135d6-7f7a-4cb9-8a88-3b484cf55c25)

**Comment by bobzilladev** [comment]
Hi, thanks for writing in! The library does add a [SIGINT shutdown hook](https://github.com/ngrok/ngrok-javascript/blob/main/index.js#L506) to close sockets and remove the files, but this method of invocation may be killing the process in such a way that that hook doesn't get activated. Is there a way to configure it to send an interrupt signal? Or if it is sending another type of signal a hook could be added for that as well.

**Comment by russorat** [comment]
thanks! I was using the express example from this repo. I dug in a bit and it looks like nodemon can send any signal you want: https://github.com/remy/nodemon#gracefully-reloading-down-your-script although i couldn't figure out what signal it sends by default.

I configured a nodemon.json config file with:
```
{
    "signal": "SIGINT"
}
```
and the files seemed to be reaped successfully. it does keep the folder around afterwards though and i'm not sure if we should be listening to SIGTERM as well.

**Comment by bobzilladev** [comment]
Ah, good to hear that setup is working, we can investigate listening for more signal types in the future. Thanks for sending in this feedback!

**Comment by bobzilladev** [comment]
Hello! Registering a SIGTERM hook is now merged and will be in the next release. Going to close this issue out, feel free to reopen or file another if something else comes up. Thanks for writing in!

Merged PR: https://github.com/ngrok/ngrok-javascript/pull/127
