### ISSUE TITLE
Error: Failed to convert napi value String into rust type `u32`

### ISSUE THREAD

**Issue by devxoul** [ngrok/ngrok-javascript#133]
Hi, I'm getting error:

```
Error: Failed to convert napi value String into rust type `u32`
    at Object.ngrokForward (/my-app/node_modules/@ngrok/ngrok/index.js:620:18)
    at /my-app/packages/ngrok/src/index.js:33:33
    at Object.<anonymous> (/my-app/packages/ngrok/src/index.js:44:3)
```

The code I've used:

```js
const ngrok = require('@ngrok/ngrok')
ngrok.connect({ subdomain, port })
```

Environments:

```
$ node -v
v20.11.1
$ yarn -v
4.1.1
```

Please mention me if more information is needed.
Thanks you guys for your great work :+1:

**Comment by bobzilladev** [comment]
Hi, thanks for writing in! What's happening there is it is trying to convert that argument into a port number. Something like this may work for what you are trying to do (a modification of [examples/ngrok-forward-minimal.js](https://github.com/ngrok/ngrok-javascript/blob/main/examples/ngrok-forward-minimal.js))

```
const ngrok = require("@ngrok/ngrok");
const subdomain = 'localhost';
const port = 8080;
(async function () {
  const listener = await ngrok.forward({ host: subdomain, port: port, authtoken_from_env: true });
  console.log(`Ingress established at: ${listener.url()}`);
})();
```

**Comment by bobzilladev** [comment]
Hello again,

[This change](https://github.com/ngrok/ngrok-javascript/pull/134) will be in the next release, which will try to `parseInt` a string port in the Config at that point as a convenience. Thanks for the feedback!

**Comment by bobzilladev** [comment]
Going to close out this issue, feel free to write in if anything else comes up. Thanks again!
