### ISSUE TITLE
`The specified module could not be found` error on Windows

### ISSUE THREAD

**Issue by chetbox** [ngrok/ngrok-javascript#142]
Many of our Windows users are getting the following error when initialising our Electron app which includes this library:

```
The specified module could not be found.
\\?\C:\Users\[redacted]\AppData\Local\[app_name]\app-5.3.1\resources\app.asar.unpacked\.webpack\renderer\node_modules\@ngrok\ngrok-win32-x64-msvc\ngrok.win32-x64-msvc.node
```

Note that we are using Electron Forge and have set in `forge.config.js`:

```js
module.exports = {
  packagerConfig: {
    asar: {
      unpack: '*.node'
    }
}
```

Which works perfectly fine for other native libraries like `serialport`.

I have tried installing the same application on our own Windows 10 and Windows 11 machines and I can confirm:
1) The file exists
2) The module is loaded
3) I can connect to Ngrok

What could be causing this?

Does the MSVC runtime need to be installed on the target computer? I can't see any like that in the documentation but I'm at a loss as to what else could be causing this problem. 

Edit: I am using version 1.2.0

**Comment by chetbox** [comment]
I have tracked the issue down on a clean Windows install. The problem was indeed that the Microsoft Visual C++ Redistributable is not installed.

Our workaround for now is bundling `vcruntime140.dll` into the application in the same folder as `ngrok.win32-x64-msvc.node`.

I think this should be, at the very least, mentioned in the installation instructions. Ideally this library would bundle the DLL file for machines where MSVC is not installed.

**Comment by salilsub** [comment]
I've opened an issue to update our README with this information. I don't think we would want to bundle this in the SDK since it would not be relevant for non-Windows users.

**Comment by chetbox** [comment]
There is a subpackage specifically for each architecture/platform pair and I think it would make a lot of sense to bundle the DLL in the Windows MSVC one.

**Comment by lannodev** [comment]
I have the same problem with an Electron app. In my case, I'm building a Windows APPX for the Microsoft Store, and the certification failed. I think it is impossible to install the MSVC runtime on Windows apps. Is there any solution to this problem? Should I create a new issue?

All the best

**Comment by chetbox** [comment]
We have decided to bundle the MSVC DLL in our app separately and that seems to work for users that don't have it installed.

**Comment by lannodev** [comment]
@chetbox Please, can you help me how to bundle the MSVC DLL?

**Comment by chetbox** [comment]
We have a copy of the DLL checked into the repo. During the build the DLL is copied into the `node_modules/@ngrok/ngrok-win32-x64-msvc` folder. This is the same folder as the `.node' native library which will look here first for DLLs when it loads.

Our solution use an Electron Forge plugin that looks like this:

```js
// NgrokMsvcWorkaroundPlugin.js
class NgrokMsvcWorkaroundPlugin extends PluginBase {
  name = 'ngrok-msvc-workaround';
  getHooks() {
    return {
      async prePackage(_forgeConfig, platform, arch) {
        // Bundle MSVC runtime for Windows builds in case it is not installed on the target machine
        if (platform === 'win32') {
          await fs.promises.cp(
            'tools/windows-dlls/vcruntime140.dll',
            `.webpack/${arch}/renderer/node_modules/@ngrok/ngrok-win32-x64-msvc/vcruntime140.dll`,
          );
        }
      },
    };
  }
}

module.exports = NgrokNativeModulesWorkaroundPlugin;
```

Then be sure to import it and include it in the `plugins` section of your Forge config.

**Comment by lannodev** [comment]
Are you copying only the vcruntime140.dll file?

**Comment by chetbox** [comment]
> Are you copying only the vcruntime140.dll file?

For our specific use case we're copying all the `node_modules/@ngrok` files as well but we have quite a complex build system. Your build system should already be including the `@ngrok/*` dependencies. This DLL is included in addition to that.

**Comment by lannodev** [comment]
Thank you 😊
