### ISSUE TITLE
Cannot detect disconnections

### ISSUE THREAD

**Issue by ArthyFlette** [ngrok/ngrok-javascript#155]
Hi,

I am trying to detect when the ngrok connection drops with this code:
```
const listener = await ngrok.forward({ 
  
	  addr: config.ngrok.port, 
  
	  authtoken: config.ngrok.token,
  
	  on_status_change: (addr, error) => {
  
		  console.log(`disconnected, addr ${addr} error: ${error}`);
  
	  },
  
  });
```

console.log in on_status_change never triggers

Is there anything wrong with this code ?

**Comment by jrobsonchase** [comment]
Thanks for the issue!

This looks like it's somewhere between a bug and a documentation issue. The field is actually `onStatusChange`, and it should be a function that only takes a single string describing the change that occurred, e.g.
```js
{
    onStatusChange: (status) => {
        console.log(`status change: ${status}`);
    },
}
```

**Comment by ArthyFlette** [comment]
works like a charm, thanks :)

**Comment by russorat** [comment]
@ArthyFlette glad to hear!
